#!/bin/bash
source /tmp/.setenvmf
. $MFCOBOL/bin/cobsetenv
escwaState=$MFCOBOL/.escwastate
if [ ! -f $escwaState ]; then
    $COBDIR/bin/escwa --BasicConfig.MfRequestedEndpoint="tcp:*:10086" --BasicConfig.InsecureAutoSignOn=true --write=true
    touch $escwaState
else
    $COBDIR/bin/escwa
fi