#!/bin/bash
source /tmp/.setenvmf
. $MFCOBOL/bin/cobsetenv
fsPID=$MFCOBOL/.fspid
if [ -f "$fsPID" ]; then
  pid=$(cat "$fsPID")
  if kill -0 "$pid" 2>/dev/null; then
    kill "$pid"
  else
    echo "Process not running"
  fi
else
    echo "PID file not found"
fi
sleep 5
if kill -0 "$pid" 2>/dev/null; then
    kill -9 "$pid"
fi