#!/bin/bash
source /tmp/.setenvmf
. $MFCOBOL/bin/cobsetenv
mfdsState=$MFCOBOL/.mfdsstate
if [ ! -f $mfdsState ]; then
    $COBDIR/bin/mfds64 --UI-on
    $COBDIR/bin/mfds64 --listen-all
    touch $mfdsState
fi
$COBDIR/bin/mfds64